services:

  server-db:
    image: 'postgres:16.1-alpine3.19'
    container_name: server-db
    ports:
      - 5432:5432
    volumes:
      - ../db/:/docker-entrypoint-initdb.d
      - postgres-server:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rrhh
      - POSTGRES_USER=rrhh
      - POSTGRES_PASSWORD=rrhh
    networks:
      - server-db
  
  server:
    build:
      context: ../server/reactSharpAPI/
    container_name: server
    environment:
      - DB_HOST=server-db
      - DB_PORT=5432
      - DB_NAME=rrhh
      - DB_USER=rrhh
      - DB_PASSWORD=rrhh
    ports:
      - 5001:5001
    depends_on:
      server-db:
        condition: service_started
    healthcheck:
      test: curl --fail http://localhost:5001/react-sharp-api/v1/status || exit 1
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - server-db
      - web-server


  web:
    build:
      context: ../web/react-app/
    container_name: web
    environment:
      - REACT_APP_API_URL=http://localhost:5001/react-sharp-api/v1
    ports:
      - 3000:3000
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - server-db
      - web-server

volumes:
  postgres-server:

networks:
  web-server: {}
  server-db: {}